default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: Locadora
  password: password

development:
  <<: *default
  database: Locadora_development
  username: Locadora
  password: password

test:
  <<: *default
  database: Locadora_test
  username: Locadora
  password: password

production:
  <<: *default
  database: Locadora_production
  username: Locadora
  password: <%= ENV['LOCADORA_DATABASE_PASSWORD'] %>
